### ISSUE TITLE
Define configuration management strategy

### ISSUE THREAD

**Issue by genjohnson** [uiowa/rusty#158]
Define and document the process for moving & management configuration between environments.

https://www.drupal.org/docs/8/configuration-management/managing-your-sites-configuration

## Config Requirements
- Define default config - required
- Diff between default and active config - optional/enhancement
- Revert to default config - optional/enhancement
- Override default config - required

**Comment by richardbporter** [comment]
# Tasks

- [ ] Remove SYNC config dir from local/remotes

It will be easier to manage config if we only have one directory. Since VCS is required on AC, we should just use this.

**Comment by richardbporter** [comment]
This is a good reference: https://blt.readthedocs.io/en/latest/configuration-management/

**Comment by richardbporter** [comment]
Exporting configuration back to the profile can be a pain. We should evaluate drupal console and/or features to see if they make the process any easier. 

https://www.drupal.org/docs/8/creating-custom-modules/include-default-configuration-in-your-drupal-8-module

**Comment by richardbporter** [comment]
One option for sites is to use the configuration override system for less-complicated use cases.

https://www.drupal.org/docs/8/api/configuration-api/configuration-override-system

**Comment by richardbporter** [comment]
Some observations on Drupal Console:

- It requires us to downgrade a few Symfony packages. Could be problematic.
- It's slow.
- While the export content type and single commands were nice, they didn't seem to be stripping uuids and hashes correctly.

**Comment by joewhitsitt** [comment]
I have watched two videos today: 

Sharing and overriding config in a Drupal 8 multisite by Jan Lemmens
===

- https://youtu.be/HSq3EPvrgys?t=1827
- Same UUID across all sites in multisite.
- Shared config (not profile) with config_split for site specific config.
- https://www.drupal.org/project/improved_multi_select makes config_split UI usable.
- Allows minor extends of functionality.

Config Management for Drupal Multi-site and Distributions
===

- https://www.youtube.com/watch?v=T0uNpkM1M9M
- They have Acquia SiteFactory for their "Standard Service," and pantheon sites for special custom.
- They use a combination of profile/distributions.
  - Profile is agnostic to its location.
  - Distribution per location (acquia, pantheon)

## UCDAVIS Profile

- Config that will be default on install but they expect will change on a site by site basis. user.role.\*, system.theme, block.block.\*, \*.settings

  ### Custom Modules Config

    - Only set default config, expect sites to change it.

  ### Features

    - We own it and we will revert if we want.
    - Article content type, views, pathauto patterns, taxonomies etc.
      - They had a bug with a RSS view. They fixed it and were confident that they could revert it for all.
      - They can extend within the feature to handle specific sites (e.g. engineering group of sites get a maker bot file upload field).
    - Development Workflow:
      - Create new field on content type.
      - Export config.
      - Commit config.
      - Update hook to import/revert individual config files.
      - New permissions for a role via update hook and get set in default profile configuration for new sites.

  ### Mini Permissions/Config Pages/Form

    - Instead of opening up administer permissions, etc., they create mini config pages/forms to allow sites to set custom permissions config.
    - For permissions, they are usually no consequence type things like Editor can't publish articles.

## TOOLS

- Configuration Manager
- Features
- Configuration Update Manager Module
- Lock Features - Site builders can create new types, views, etc but are not allowed to edit existing
  - github.com/ucdavis/sitefarm_seed
- Configuration Read-Only anything with sf_ gets locked
- Config Ignore (site name, block placement)
- Entity Clone (Not only "node clone by editors, but site builders can "Fork" article content type to make it their own).

## Other Notes
- Config Install/Optional
  - Try to get as much into install as you can. If it blows up, it will tell you which file and just move that to optional. That has worked for them thus far.
- Not using layouts/panels currently.
- Biggest challenge - getting developers knowledgable with where to put particular config.
- Stuff that is default config and breaks down the line - they make the decision to move that config into a feature and revert for everyone or just fix the default config for new sites and run updates for subset group of sites that want it fixed.
- This model works with inheritance if it ever makes it to core.

**Comment by joewhitsitt** [comment]
I found the second video (ucdavis, more notes) more interesting with regard to our situation for a couple of reasons:

- Instead of profile inheritance, we could use a combo of profile/distribution to handle our dividing use-cases (intranets, commerce, clas, grad, engineering, research) if needed.
- The features workflow will allow us to manage functionality at a very large scale and we can start off with our idea that every site is a standard site that you can extend. Though not as ideal, extending can happen within the feature (switch case functionality base on site variable) or by allowing sites/groups fork the functionality (entity clone).
- It shows how changes to config can be set for new/existing sites.

**Comment by richardbporter** [comment]
I think we definitely meet the this use-case for features:

> “I am building a complex platform/multi-site that needs different configuration for different sites or environments and having Features makes it all possible. 

Features will make it easier to pick and choose which config lives with which module and export it. Config update will make it easy to compare site config against initial profile config. 

Remaining questions:
- Are features extensible or should they always be reverted?
- Do we implement any sort of automated workflow for config?

The simplest approach might be just using features as a packaging/comparison utility. Sites can do a full export if necessary. The only automation we do is `updb`. Overridden sites can stay overridden and sites with exported config can export and update as necessary.

**Comment by pyrello** [comment]
It looks like this may have been covered by @joewhitsitt's recent comments, but I wanted to note that we should start including UUID's on all config files we export. Yesterday, I came across this issue where I was attempting to import config via the UI with the contents I had copied from a config file for the uiowa_paragraphs module. It was unable to update the config because the UUID was missing.

This isn't a huge issue because I was able to just export the config I needed and re-import it with the UUID that was exported, but it made me realize that the system shouldn't be creating the UUID upon the rusty profile being installed. It should be the same UUID for each shared config across all system.

**Comment by richardbporter** [comment]
We've taken the approach outlined in the docs thus far: https://www.drupal.org/docs/8/creating-distributions/how-to-write-a-drupal-8-installation-profile It says UUIDs, among other things, should be removed. 

But obviously a more robust approach is required now.

**Comment by adamdelaney** [comment]
I believe module install config is the same. The uuid and _core values should be stripped.

**Comment by adamdelaney** [comment]
@pyrello I don't think install config is suppose to be imported this way. The idea of reverting config back to an initial config state is not a core concept but can be accomplished with something like features.

**Comment by adamdelaney** [comment]
## [Features](https://www.drupal.org/project/features)
CM wrapper to export and manage config.

### Base Requirements
- [ ] Define default config - required
- [ ] Diff between default and active config - optional/enhancement
- [ ] Revert to default config - optional/enhancement
- [ ] Override default config - required

**Comment by richardbporter** [comment]
Config Split seems overly complicated to share config across multisites with the same UUID. For example, `drush si` options like `site-name` and `site-mail` don't work when installing from existing sync config. As far as I can tell, there is no way to import the split config after installation - it would need to exist in the sync dir but that won't work b/c multisites would have different split folders. It also assumes sites will have certain config in the split dir (meaning every site has a repo), something that is not true for our "standard" sites.

**Comment by adamdelaney** [comment]
At this point my vote is to package all install and custom module config using features. If a site needs to override the default configuration then it would export the entire site config to the site sync directory and manage it on it's own.

**Comment by genjohnson** [comment]
> If a site needs to override the default configuration then it would export the entire site config to the site sync directory and manage it on it's own.

@adamdelaney Maybe I'm misunderstanding how the proposed configuration management would work or the details just haven't been determined yet, but if a site required overriding a minor default config setting or two and all of the config for a site is exported due to the customization, how do we keep track of which parts of the site are *supposed* to be customized vs which should change as updates to the platform are released and how would updates to the platform be handled?

**Comment by joewhitsitt** [comment]
i don't think everything can be in features. if that was the case, changing site name, email, google analytics id, enabled theme, etc. UCDavis has these kinds of things in the profile config/install and content types/fields/views/tax in features

**Comment by adamdelaney** [comment]
@genjohnson in this scenario a site that exports config to their sync directory would have to handle any platform changes on their own.

**Comment by adamdelaney** [comment]
@joewhitsitt not all config would need to be packaged. Only default config, or config that needs to be updated at the platform level.

**Comment by adamdelaney** [comment]
If we define our features fairly granular, a site could disable a feature tracked module and essentially clone it to override functionality, storing their clone in a site repo to avoid exporting site config and managing config updates independently.

**Comment by richardbporter** [comment]
Docs on updating config for modules: https://www.drupal.org/docs/8/api/update-api/updating-configuration-in-drupal-8

**Comment by adamdelaney** [comment]
## Profile sync with config_split and config_ignore
This config strategy satisfies all the requirements. Drupal core allows you to [install a site from existing site config](https://www.drupal.org/node/2897299) from a sync folder in a profile. Any config that we define a site should `own` or override i.e. site name, would be ignored using `config_ignore`. Any site that would override functionality would configure a split and track those changes in their site repo using `config_split`.

## Advantages
- Sites can override basic config settings that are determined at the platform level.
- Sites can override entire feature sets by defining splits and managing config on it's own.
- Profile config/sync directories are supported out of core and provide a nice UI to see config diffs and import and export config.

## Disadvantages
- Sites that define config in a split uses different commands for exporting and importing.
- Sites that define a config split does not have a diff tool to see active vs stored config_split config.

**Comment by richardbporter** [comment]
https://github.com/uiowa/multisite/issues/77

**Comment by pyrello** [comment]
Hey all, I'm sorry to reopen this after all the discussion that has gone on in it. It has taken me a bit to get fully up-to-speed on the various items that have been discussed.

Here are some thoughts:

- My intention with suggesting features as a way of packaging configuration was never meant to be the total solution. It is really just a packaging tool, and an imperfect one at that. It's auto inclusion functionality shouldn't be a replacement for manually checking that the config included is the proper config. But what it does offer is the ability to selectively choose a set of configuration items to export. I have previously used it in a project similar to what we are doing with uiowa_paragraphs, and the exported modules I created with it have been successfully used to create several sites now.
- The strategy that seems to have been agreed upon in my absence is that we would dump _all_ config into the config/sync directory in favor of having some profile-level config and some module-level config. I'm not a fan of this strategy for philosophical reasons - having what amounts to module config be loaded by the profile instead doesn't seem like a good separation of concerns - and practical reasons - if we do end up creating different profiles, we'll want to split uiowa_paragraphs out of the rusty profile into its own project so that it can be shared among multiple profiles.
- I think that a better approach is to have module config live in its module and any config that is specific to the profile which overrides or implements the module live in the profile config. For example, the config files which provide the fields and paragraph bundles that make up the uiowa_paragraphs system should live there. The config that creates a page content type and adds the paragraph-based body field to it should live in the profile.

I appreciate that a lot of work has been done on this already and I regret that the timing of my surgery did not allow for me to chime in on this sooner. I'm ready to put my money where my mouth is and figure this out to prove the concept that I am trying to push. In the meantime, I welcome any of your thoughts or concerns.

**Comment by richardbporter** [comment]
I think that is the approach we originally intended. It sounds good in theory but is a pain in practice. We actually did some work on it in a PR but closed it: https://github.com/uiowa/rusty/pull/203

I think we should follow what Acquia _strongly recommends_ for multisite applications: https://blt.readthedocs.io/en/latest/configuration-management/ We've modified it to fit our current architecture but it is the same principal: avoid the higher development and maintenance overhead of features.

The current strategy allows for:

- sites using the rusty profile to leverage the paragraphs/page configuration as-is
- sites using the rusty profile to override the paragraphs/page configuration via a split
- sites using a different profile to configure paragraphs/page as needed

If you'd like to use the existing paragraphs/page configuration in rusty, I see two options:
- use rusty
- copy the existing configuration from rusty into the grad profile and modify as needed

That seems flexible enough to account for our use-cases. I'm not sure what value features is adding.

**Comment by pyrello** [comment]
@richardbporter It really doesn't matter to me if we use features or not. I don't think that it is necessary for us to be on the same page about whether we use it, since it is purely a development tool for the purpose of bundling configuration exports together. Beyond that, it has no value IMO. I'm not trying to make the case for using features and including it in any official development workflow.

By putting all the configuration that would normally go in uiowa_paragraphs/config into rusty/config, we are forcing a situation where the only way that can be shared with another profile is by the copy/paste method above. As changes are made, new paragraph types are added, they will all get added to rusty and not the uiowa_paragraphs module. Then, if I am using those same configurations for a separate profile, I will have to repeat this copy/paste process every time. It totally defeats the point of having a module in the first place.

**Comment by richardbporter** [comment]
Yep, I agree with that. We're cloning a site essentially: https://www.drupal.org/node/2897299

Might be easier to discuss this in-person.

**Comment by pyrello** [comment]
Happy to meet in-person to discuss this.

I guess my understanding of how configuration management would be used, in the instance where you would be using the "Install from existing configuration" option indicated in the link above is for sites that are exactly the same. Like, you have a prod, staging, and possibly multiple local development versions of the site. They are all the same site. They would share a site uuid.

But it sounds like maybe the intention is to use the "install from existing configuration" option as a deployment vehicle? Maybe I'm not understanding correctly.

**Comment by richardbporter** [comment]
The intention is to easily manage default or "standard" configuration across a large number of multisites. Then individual sites can split from the default if needed. Its very similar to the method described in the BLT docs: https://blt.readthedocs.io/en/latest/configuration-management/#configuration-split-workflow

It is possible to use features right now to package up shared module configuration, i.e. those we've moved out of rusty or any new ones. I don't have a problem with adding it as a dev dependency.

**Comment by pyrello** [comment]
I'm working my way through this series of articles: http://chocolatelilyweb.ca/blog/managing-shared-configuration-part-1-configuration-providers

It's fairly lengthy, but it is also written very recently and covers a lot of the modules that have been created to cover the missing Drupal distribution use-case for D8 CM.

**Comment by adamdelaney** [comment]
## Module splits

One idea that I've tested is to create feature/module config_splits. For example we could create a news config_split that held the news content type and fields and add the config to a complete split in a news config_split. This allows config objects to be stored in a folder with that module and allows the config to be turned off and on. If a split is activated/deactivated you would have to run a `drush cim` to add/remove the functionality. 

This essentially accomplishes providing default config in more modular approach. It allows us to export config using a UI and still leverages Drupals core CM tooling.

There may be issues with shared field storages and other shared config. I think we need to determine if we are going to use multiple profiles or just stick with 1 profile.

**Comment by pyrello** [comment]
@adamdelaney This article (a later one in the series I posted before) covers some of the challenges of modular development: http://chocolatelilyweb.ca/blog/managing-shared-configuration-part-7-core-configuration

One thing that is discussed is using the [Configuration Share](https://www.drupal.org/project/config_share) module to provide config that waits to be installed until its needed. Essentially, it is like optional config, but instead of being checked to see if it's dependencies are met each time an extension is installed, it is only installed if it is called as a dependency AND its not already installed. Not a perfect solution, by any means, but possibly a good starting point.

I highly recommend reading all 8 of the articles in the above linked post, as well as the related issues on drupal.org.  It is very illuminating about the current state of configuration as well as giving some hints about where it may be headed.

**Comment by richardbporter** [comment]
Thanks for sharing. Very interesting. The three-way merge sounds like our ideal scenario. However, we need to move forward on our current site requirements with our current workflow. This doesn't preclude us from changing in the future.

**Comment by pyrello** [comment]
@richardbporter I am going to continue to pursue this idea to figure out what combination of modules this would require and how the workflow would go. Since this might take a while and the rusty repo is likely to change quite a bit in the meantime, I think it might be best for me to fork the rusty repo and work on these changes in the fork. Eventually those changes could be ported back to rusty if we decided to adopt that strategy eventually.
