### ISSUE TITLE
[META] UI Events

### ISSUE THREAD

**Issue by genjohnson** [uiowa/rusty#173]
- [x] Elicit & document requirements for UI Events 
- [x] Implement UI Events
- [ ] Provide documentation for content contributors

**Comment by joewhitsitt** [comment]
i know this doesn't follow the meta checklist and isn't part of the 1.0 timeline, but there is an initial uiowa_events branch available for testing. it implements page, block, paragraph and uses a custom content entity for the shared form. it does not have today/week/month/archive routing

**Comment by joewhitsitt** [comment]
initial MVP has been merged. closing and will create follow-up tasks for rusty documentation and uiowa_bootstrap base styles.
