### ISSUE TITLE
[META] UI Articles

### ISSUE THREAD

**Issue by genjohnson** [uiowa/rusty#174]
- [ ] Elicit & document requirements for UI Articles (I'm making up this name for the sake of creating the issue. If something else makes more sense, we'll use that)
- [ ] Implement UI Articles
- [ ] Provide documentation for content contributors

**Comment by joewhitsitt** [comment]
Mark said that OSC articles would be paragraph based but also that a news content hub is currently postponed.

**Comment by joewhitsitt** [comment]
OSC is backing away from top-down news for now. We are going to move forward with a basic news content type for local news.

**Comment by joewhitsitt** [comment]
branch started https://github.com/uiowa/sitenow/tree/articles
