### ISSUE TITLE
[META] UI People

### ISSUE THREAD

**Issue by genjohnson** [uiowa/rusty#175]
- [ ] Elicit & document requirements for UI People 
- [ ] Implement UI People
- [ ] Provide documentation for content contributors
