### ISSUE TITLE
[META] Paragraph Enhancements

### ISSUE THREAD

**Issue by pyrello** [uiowa/rusty#197]
@bspeare, @mark-bennett-uiowa and I were reviewing the current paragraphs UI implementation and have some ideas for improving it:

- [ ] Default the Administrative label for sections to the bundle type (Section). Modify the UI to show the Administrative label in place of the bundle type at the top of the section. Allow editing the administrative label to happen in-place where it shows and not as a separate field.
- [ ] Change page level "Content Blocks" field label to "Sections."
- [ ] Change section level "Content Blocks" field label to "Widgets."
- [ ] Remove "to Content Blocks" from the drop-down button for adding paragraphs to each section.
- [ ] Change third_party_settings > field_group > group_uip_settings > weight from 2 to 1 in core.entity_form_display.paragraph.section.default.yml
- [ ] Change "Settings" label to "{Paragraph type} Settings" in core.entity_form_display.paragraph.{paragraph_type}.default.yml

**Comment by adamdelaney** [comment]
I would suggest creating a new PR with these changes for review.

**Comment by pyrello** [comment]
@adamdelaney Sounds good. I will create a PR for checking these. I was thinking of this as more like a jumping off point for discussing these changes if anyone had any thoughts about them.

**Comment by adamdelaney** [comment]
> Default the Administrative label for sections to the bundle type (Section). Modify the UI to show the Administrative label in place of the bundle type at the top of the section. Allow editing the administrative label to happen in-place where it shows and not as a separate field.

- I think the bundle type should still be part of the label. Possibly `Section: Admin Title`.
- I'm not sure what is meant by `Allow editing the administrative label to happen in-place where it shows and not as a separate field`.

**Comment by adamdelaney** [comment]
> Change page level "Content Blocks" field label to "Sections."
> Change section level "Content Blocks" field label to "Widgets."

I'm fine with these changes.

**Comment by adamdelaney** [comment]
> Remove "to Content Blocks" from the drop-down button for adding paragraphs to each section.

Not sure what this means... maybe provide a marked up screenshot?

**Comment by adamdelaney** [comment]
> Change third_party_settings > field_group > group_uip_settings > weight from 2 to 1 in core.entity_form_display.paragraph.section.default.yml
> Change "Settings" label to "{Paragraph type} Settings" in core.entity_form_display.paragraph.{paragraph_type}.default.yml

Not sure what these mean.. maybe provide a marked up screenshot.

**Comment by joewhitsitt** [comment]
If we are changing labels, we should change machine names as well so they are consistent. I am okay with the name changes.

I am okay with the field weight changes.

**Comment by pyrello** [comment]
> I'm not sure what is meant by `Allow editing the administrative label to happen in-place where it shows and not as a separate field.`

@adamdelaney Here are a couple screenshots to illustrate what I mean about the edit-in-place functionality:
<img width="247" alt="screen shot 2018-11-30 at 10 46 43 am" src="https://user-images.githubusercontent.com/709009/49302753-901a2a00-f48d-11e8-8660-7cf7c1c59268.png">
<img width="273" alt="screen shot 2018-11-30 at 10 47 13 am" src="https://user-images.githubusercontent.com/709009/49302758-94dede00-f48d-11e8-9dd2-4d2dc7b09003.png">

These are very basic examples.

**Comment by pyrello** [comment]
> > Remove "to Content Blocks" from the drop-down button for adding paragraphs to each section.
> 
> Not sure what this means... maybe provide a marked up screenshot?

<img width="291" alt="screen shot 2018-11-30 at 10 50 38 am" src="https://user-images.githubusercontent.com/709009/49302881-d5d6f280-f48d-11e8-835c-64b634df4949.png">

**Comment by adamdelaney** [comment]
@pyrello in place editing of the admin title would be pretty slick, however I would still prefer if the bundle name would always exist, since that is helpful information.

**Comment by pyrello** [comment]
@adamdelaney When you say you would prefer for the bundle name to always exist, do you mean that you think it should always be shown to the user?

**Comment by adamdelaney** [comment]
@pyrello I'm not sure we need to add parent context to the add widget for a couple of reasons.
1) There are different widgets to add paragraph bundles. It's possible we use buttons instead of dropdowns.
2) Complex logic may be required to find the parent bundle.
3) I'm not convinced how helpful this extra text really is.

**Comment by adamdelaney** [comment]
> When you say you would prefer for the bundle name to always exist, do you mean that you think it should always be shown to the user?

Yes, knowing the bundle type can be useful.

**Comment by pyrello** [comment]
> @pyrello I'm not sure we need to add parent context to the add widget for a couple of reasons.
> 
>     1. There are different widgets to add paragraph bundles. It's possible we use buttons instead of dropdowns.
> 
>     2. Complex logic may be required to find the parent bundle.
> 
>     3. I'm not convinced how helpful this extra text really is.

@adamdelaney I'm not sure what you are referring to with this comment.

**Comment by adamdelaney** [comment]
Oh sorry, it looks like you are suggesting to remove this, not add it. I mis-understood the request. I'm fine with removing.

**Comment by adamdelaney** [comment]
Just wondering where we are on this, I was looking into packaging this stuff into features and I didn't want to have to double up on the work in case new fields are created or config is being updated.

**Comment by adamdelaney** [comment]
Looks like you are out this week, I'm moving forward on re-packaging paragraphs into features. Check in with me when you get back if you want.

**Comment by pyrello** [comment]
@adamdelaney Is there a new PR I should look at? Or has this been merged into master?

**Comment by adamdelaney** [comment]
@pyrello , I think we have decided to re-engineer how default config works and remove features as part of the workflow. See https://github.com/uiowa/rusty/issues/158
