### ISSUE TITLE
Profile inheritance [meta]

### ISSUE THREAD

**Issue by adamdelaney** [uiowa/rusty#34]
See issue: https://www.drupal.org/project/drupal/issues/1356276.

## Testing
- [x] Test that module dependencies are properly enabled.
- [x] Test that a child profile can only see modules and themes available to it's profile and parent/parents.
- [x] Test that hook implementations work from parent/~~parents~~.
- [x] ~~Document and~~ test how profile install configuration works.

**Comment by richardbporter** [comment]
Also, the patch needs to be applied at the application level: https://github.com/uiowa/uiowa801/issues/8

**Comment by richardbporter** [comment]
Testing with 8.6.2 patch.

https://www.drupal.org/project/drupal/issues/1356276?page=1#comment-12827004

**Comment by richardbporter** [comment]
Optional config does not seem to be installed from base profile.

**Comment by richardbporter** [comment]
The patch seems to work as expected minus the optional config issue. It could be very useful in our attempt to build a base platform that can be extended by suites of sites. However, there is talk of it not landing in core. We should continue working on one platform for now and follow the trajectory of the issue.
