### ISSUE TITLE
[META] Documentation

### ISSUE THREAD

**Issue by genjohnson** [uiowa/rusty#88]
## Todo
- [x] Determine authoritative source for documentation
- [X] Identify tasks/features to document
~~Create documentation~~
- [x] Decide if documentation should be available within each website. How would this work for documentation which may be site-specific?

**Comment by bspeare** [comment]
I would prefer to see documentation all in one place like https://its.uiowa.edu/sitenow#!how-to-and-support.  What percentage of the traffic to these individual support articles is from Google?  I know that we have support pages where the traffic from Google is over 55%.  Having public documentation is a great secondary option for users who did not see the link to documentation while they are logged in to their site.

**Comment by genjohnson** [comment]
I'm not a big fan of continuing to use the ITS website as the authoritative source for our documentation for a couple of reasons:
1. It is very difficult/nearly impossible to structure the articles in an easy-to-search way. Many of the support articles that are escalated to the Web Services team are resolved by sharing a link to a support article.
2. Since we're sharing a common install profile, not all of the websites which the support articles will apply to will be considered "SiteNow" websites, so I'm not sure it makes sense to send all Drupal site users to the SiteNow service section. 

I'm currently having a conversation with Hostmaster about using the URL pattern *.sites.uiowa.edu, similar to the other URL patterns used on the SiteNow service. Assuming that pattern is approved, what if we had a development team/service agnostic, publicly available support site at something like help.sites.uiowa.edu or drupal-help.sites.uiowa.edu? To begin with I envision this would be a relatively simple website with only documentation that applies to all sites, but it could be evolved into a more robust solution with filtered documentation lists for custom sites or other functionality (like the feed into sites like SiteNow has now) if needed later.

**Comment by joewhitsitt** [comment]
so i was thinking about writing some paragraphs docs. this meta seems dated based on recent conversations. what is the current consensus?

**Comment by joewhitsitt** [comment]
The built-in help and tour modules sounds appealing to me, but there is a lot of stuff already included in help that may be distracting to site editors. I don't see an easy way to pick and choose what help docs editors will see. `Use the administration pages and help` is the only permission I see for this.

**Comment by joewhitsitt** [comment]
For now, just to get the ball rolling I have started a docs directory with PR #198  in rusty to house some documentation. I figured markdown is pretty easy for us to write (convert if need be) and we can use the github pages functionality until we settle on something else. public/stays with code.

**Comment by richardbporter** [comment]
The help module does seem to have a lot of cruft that would require us to unset. Writing docs in hook_help() would be unpleasant as well. I'm not seeing a hook_help_alter() for customizations.

Centralizing docs would require a lot of screenshots. Its easy for those to become outdated when elements change location, appearance, etc. Its not possible to override docs for customized sites with this method - it just needs to be duplicated.

The tour module can attach tips to elements on a page. When elements move around or change appearance, the tip will follow (as long as the selector remains the same). Tours are configuration and can be customized per site by exporting, changing and importing. 

I wonder if we could leverage Travis to aggregate tour YAMLs into markdown files (or similar) and publish to GitHub pages. It would be text-only and very basic but we'd avoid duplicating work and have _some_ publicly accessible docs.

**Comment by joewhitsitt** [comment]
Thanks for chiming in.

So far screenshots have been a pain. (removing masquerade from the toolbar, changing the env indicator from LANDO, etc.). I haven't done some because I am unsure if labels, field weights will change.

I like your ideas about the tour module, but I don't think all docs can/should be captured in a tour.

So maybe a combo of text-only docs and parsed tours?

**Comment by richardbporter** [comment]
I see what you mean, like top-level generic docs. For example the intro for your GA docs: https://github.com/uiowa/rusty/pull/198/files#diff-429b0df49aede06e3a824ba849f0512d

However, that is all documented inline by the module itself, so it seems like a lot of duplication to me.
![image](https://user-images.githubusercontent.com/1068523/49531230-7444c880-f87f-11e8-9527-93ee3ec98e2b.png) I think the solution to that is to keep top-level docs minimal and instructing people to refer to inline docs and/or tours while logged in. Perhaps top-level docs should have very few screenshots.

Also, since the ITS site is not an appropriate place to put docs and there is no alternative site at this point, I think we should use GitHub pages as the source for right now. Markdown is easy to use and the web interface is very handy. This does not prevent us from pulling docs into the site or moving thins at a later time. This gives developers a place to write docs as we add new features.

**Comment by richardbporter** [comment]
We should spin off individual tasks for the categories listed in this issue description once #198 is merged and then close this issue.
